## As of right now, this playbook only supports
## running the runc integration testing from
## github.com
#
## Requirements:
##      - go1.8.linux-amd64.tar.gz in local dir
##      - runc dir from github.com in local dir
- hosts: all
  tasks:
  - set_fact:
      real_ansible_host: "{{ ansible_host }}"
  - name: Setup proper directory structure for runc
    file:
      path: /home/admin/src/github.com/opencontainers
      state: directory
  - name: Setup proper directory structure for bats
    file:
      path: /home/admin/src/github.com/sstephenson
      state: directory
  - name: Edit sudoers file so admin can run rsync
    lineinfile:
      dest: /etc/sudoers
      line: 'admin ALL= NOPASSWD:/usr/bin/rsync'
  - name: Copy go tarball to atomic host
    synchronize:
      dest: /home/admin/go1.8.linux-amd64.tar.gz
      src: ./go1.8.linux-amd64.tar.gz
  - name: Copy runc github directory to atomic host
    synchronize:
      dest: /home/admin/src/github.com/opencontainers/runc
      src: ./runc/
  - name: Copy bats github directory to atomic host
    synchronize:
      dest: /home/admin/src/github.com/sstephenson/bats
      src: ./bats/
  - name: Install go
    unarchive:
      src: /home/admin/go1.8.linux-amd64.tar.gz
      dest: /usr/local
      copy: no
  - name: Add go to PATH env variable
    lineinfile:
      dest: /home/admin/.bashrc
      line: 'export PATH=$PATH:/usr/local/go/bin'
      insertafter: 'EOF'
      regexp: 'export PATH=\$PATH:/usr/local/go/bin'
      state: present
  - name: Add go to GOPATH env variable
    lineinfile:
      dest: /home/admin/.bashrc
      line: 'export GOPATH=/home/admin:/home/admin/src/github.com/coreos/etcd/gopath'
      insertafter: 'EOF'
      regexp: 'export GOPATH=/home/admin:/home/admin/src/github.com/coreos/etcd/gopath'
      state: present
  - name: Source the .bashrc file
    shell: source /home/admin/.bashrc
  - name: Let admin own the testing directory
    file:
      path: /home/admin/src
      owner: admin
      group: admin
      recurse: yes
  - name: Change helpers.bash INTEGRATION_ROOT for runc integration testing
    lineinfile:
      dest: /home/admin/src/github.com/opencontainers/runc/tests/integration/helpers.bash
      regexp: 'INTEGRATION_ROOT='
      line: 'INTEGRATION_ROOT=/home/admin/src/github.com/opencontainers/runc/tests/integration'
  - name: Change helpers.bash RUNC path for runc integration testing
    lineinfile:
      dest: /home/admin/src/github.com/opencontainers/runc/tests/integration/helpers.bash
      regexp: 'RUNC='
      line: 'RUNC=/usr/bin/runc'
  - name: Change helpers.bash GOPATH for runc integration testing
    lineinfile:
      dest: /home/admin/src/github.com/opencontainers/runc/tests/integration/helpers.bash
      regexp: 'GOPATH='
      line: 'GOPATH=/home/admin'
  - name: Unlock ostree so we can change /tmp (req. for integration testing)
    shell: "ostree admin unlock"
  - name: Move /tmp to a new location
    shell: "mv /tmp /tmp_moved"
  - name: Create new /tmp dir
    file:
      path: /tmp
      state: directory
  - name: Bind mount new /tmp dir to old /tmp dir's symlink
    shell: "mount --bind /sysroot/tmp /tmp"
  - name: Install bats
    command: bats/install.sh /usr/local
    args:
      chdir: /home/admin/src/github.com/sstephenson
  - name: Create reports dir
    file:
      path: /home/admin/src/github.com/opencontainers/runc/reports
      state: directory
