## This playbook sets up your environment for
## proper running of fedora_atomic_playbook.yaml
#
## Result:
##      - go1.8.linux-amd64.tar.gz in local dir
##      - runc dir from github.com in local dir with proper commit
##      - bats dir from github.com in local dir
- hosts: all
  tasks:
  - name: Get go tarball
    get_url:
      url: https://storage.googleapis.com/golang/go1.8.linux-amd64.tar.gz
      dest: ./
  - name: Clone runc git directory
    git:
      repo: https://github.com/opencontainers/runc
      dest: ./runc
      version: "{{ runc_commit }}"
  - name: Clone bats git directory
    git:
      repo: https://github.com/sstephenson/bats
      dest: ./bats
      refspec: '+refs/pull/161/head:refs/remotes/origin/pr/161'
      version: c575354
